# git branches to trigger build off of
# https://docs.microsoft.com/azure/devops/pipelines/process/pipeline-triggers
trigger:
  - dev
  paths:
    exclude:
      - README.md
      - LICENSE
      - .github/
      - .vscode/
      - docs/
      - media/
      - .gitignore

# Do not trigger builds on PRs
pr: none

# call shared template
extends:
  template: azure-pipeline-shared.yml